
server:
  servlet:
    context-path: /sky
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: RMNCrtr4210!
    url: jdbc:postgresql://localhost:5432/sky
    username: postgres
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: true
        show_sql: false
      
  main:
    allow-circular-references: true
